apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2021-09-12T09:32:21Z","labels":{"app":"redis-service"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:ports":{".":{},"k:{\"port\":6379,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{".":{},"f:app":{}},"f:sessionAffinity":{},"f:type":{}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2021-09-12T09:32:21Z"}],"name":"service-redis-alpine","namespace":"smartivr","resourceVersion":"7644352","selfLink":"/api/v1/namespaces/smartivr/services/service-redis-alpine","uid":"ea62af7d-ff22-440d-9e9c-31c70e56820b"},"spec":{"clusterIP":"10.43.31.140","ports":[{"port":6379,"protocol":"TCP","targetPort":6379}],"selector":{"app":"redis-alpine"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2021-11-29T03:37:31Z"
  labels:
    app: redis-service
  name: service-redis-alpine
  namespace: apm-server
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-alpine
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}